### ISSUE TITLE
samples/onnx_accelerator_sample1: missing instructions for installing dependencies

### ISSUE THREAD

**Issue by jwoehrle** [aws-samples/ml-edge-getting-started#17]
### Describe the issue

I'm trying to follow the process explained in samples/onnx_accelerator_sample1/Greengrass.md, however during the step `npx projen` I receive the following error message:

> ❯ npx projen
> 👾 default | python .projenrc.py
> Traceback (most recent call last):
>   File "/Users/<...>/development/ml-edge-getting-started/samples/onnx_accelerator_sample1/.projenrc.py", line 18, in <module>
>     from projen.awscdk import AwsCdkPythonApp
> ModuleNotFoundError: No module named 'projen'

after creating a new python venv and running `pip install -r requirements.txt` and `pip install -r requirements-dev.txt` it works.

It seems like the installation of the python dependencies is missing from the instructions?

### Links

[samples/onnx_accelerator_sample1/Greengrass.md](https://github.com/aws-samples/ml-edge-getting-started/blob/main/samples/onnx_accelerator_sample1/Greengrass.md)

**Comment by krokoko** [comment]
Hi @jwoehrle thank you for the feedback!

I just updated the documentation both for Greengrass/IoT Jobs to make the installation steps more clear.
Please let me know if you are still facing an issue.

Thanks !

**Comment by krokoko** [comment]
Closing as no answer from @jwoehrle, please reopen the ticket if the issue persists
